### ISSUE TITLE
Auth Config in latest Laravel version

### ISSUE THREAD

**Issue by sayyidyofa** [fico7489/laravel-revisionable-upgrade#4]
https://github.com/fico7489/laravel-revisionable-upgrade/blob/5971f712bcd935e0ba7c4e425bb4dfef52a011e4/src/Models/Revision.php#L11

The function `revisionUser()` uses a config value that exists until Laravel v5.1, that is `auth.model`
The latest laravel version uses `auth.providers.users.model` so when I try any method an error is thrown:
`Class name must be a valid object or a string` 
 
A temporary workaround in my Laravel 7 installation is add a new value in my `config/auth.php` :
`'model' => THE_AUTH_MODEL::class`

Maybe a working solution would be to change the code in question to something that compares the laravel version, if it's newer than 5.1 then use a different config value, roughly like this:

```
if(version_compare(app()->version(),"5.1", "gt")) {
  // use new config value
 } else // use old config value
```

Related links:
https://stackoverflow.com/a/27153678/8885105
https://www.php.net/manual/en/function.version-compare.php
https://stackoverflow.com/a/35785830/8885105

**Comment by fico7489** [comment]
the issue is fixed, thanks!!!!
